<a href="https://colab.research.google.com/github/kk13332488/Deep-Learning/blob/main/MnistData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import datasets
from tensorflow.keras.utils import to_categorical

mnist = datasets.mnist
(train_x, train_y),(test_x, test_y) = mnist.load_data()
print(train_x.shape)

(60000, 28, 28)


In [ ]:
print(train_x.shape)
np.max(train_x[0]), np.min(train_x[0])

(60000, 28, 28)


(255, 0)

In [ ]:
train_x[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [ ]:
train_x = train_x.reshape(-1,784) # 28x28 데이터를 1x784로 flatten 시킨다.
test_x = test_x.reshape(-1,784)

In [ ]:
train_x.shape, test_x.shape

((60000, 784), (10000, 784))

In [ ]:
train_x = train_x / 255 #mini-max 표준화이다. min값이 0이기 때문에 분모가 255-0 = 255가 된다.
test_x = test_x / 255

In [ ]:
train_x[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [ ]:
np.min(train_x[0]), np.max(train_x[0]) #최소값이 0, 최대값이 1로 표준화 된 것을 확인할 수 있다.

(0.0, 1.0)

In [ ]:
print(train_y[0])

5


In [ ]:
train_y, test_y

(array([5, 0, 4, ..., 5, 6, 8], dtype=uint8),
 array([7, 2, 1, ..., 4, 5, 6], dtype=uint8))

In [ ]:
train_y_onehot = to_categorical(train_y)
test_y_onehot = to_categorical(test_y)
train_y_onehot[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [ ]:
from tensorflow.keras import layers
model = tf.keras.Sequential()
#output은 one-hot encoding을 했으므로, array의 원소 개수가 10개이다. 또한 input되는 데이터는 784개로 이뤄져 있다.
model.add(layers.Dense(10, activation = 'softmax', input_dim = 784))
#optimizer는 stochastic gradient descent이고, cost함수는 one-hot encoding된 categorical crossentropy함수이다.
model.compile(optimizer = 'sgd', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
#6만건을 100batch단위로 쪼개 1 epoch당 600번 학습한다.
model.fit(train_x, train_y_onehot, validation_data = (test_x, test_y_onehot), batch_size = 100, epochs = 5)

Epoch 1/5
600/600 [==============================] - 2s 2ms/step - loss: 1.5683 - accuracy: 0.5648 - val_loss: 0.7285 - val_accuracy: 0.8473
Epoch 2/5
600/600 [==============================] - 1s 2ms/step - loss: 0.6918 - accuracy: 0.8467 - val_loss: 0.5526 - val_accuracy: 0.8727
Epoch 3/5
600/600 [==============================] - 1s 2ms/step - loss: 0.5602 - accuracy: 0.8640 - val_loss: 0.4832 - val_accuracy: 0.8795
Epoch 4/5
600/600 [==============================] - 1s 2ms/step - loss: 0.4968 - accuracy: 0.8759 - val_loss: 0.4446 - val_accuracy: 0.8870
Epoch 5/5
600/600 [==============================] - 1s 2ms/step - loss: 0.4631 - accuracy: 0.8804 - val_loss: 0.4194 - val_accuracy: 0.8902


In [ ]:
model.evaluate(train_x, train_y_onehot)

1875/1875 [==============================] - 3s 2ms/step - loss: 0.4428 - accuracy: 0.8835


[0.4428195059299469, 0.8835499882698059]

In [ ]:
model.evaluate(test_x, test_y_onehot)

313/313 [==============================] - 1s 2ms/step - loss: 0.4194 - accuracy: 0.8902


[0.4193733334541321, 0.8902000188827515]

In [ ]:
predicted = model.predict(test_x)
predicted[0], test_y_onehot[0]

(array([9.8355196e-04, 3.6428715e-05, 7.2578166e-04, 3.1585908e-03,
        5.9759500e-04, 4.9443741e-04, 4.2849653e-05, 9.8301655e-01,
        6.8480603e-04, 1.0259451e-02], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32))